---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: zabbix-debian-wheezy
    image: debian:wheezy
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/version.yml
        - meta/exception.yml
scenario:
  name: debian-wheezy
