---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  vars:
    mysql_databases:
      - name: zabbix
        encoding: utf8
        collation: utf8_bin
    mysql_users:
      - name: zabbix
        password: zabbix
        priv: "zabbix.*:ALL"

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.php
    - robertdebock.mysql
    - robertdebock.httpd
