---
- name: Prepare
  hosts: all
  gather_facts: no

  vars:
    mysql_ignore_docker: no
    httpd_ignore_docker: no
    mysql_databases:
      - name: zabbix
    mysql_users:
      - name: zabbix
        password: zabbix
        priv: "zabbix.*:ALL"
    zabbix_server: present
    zabbix_web: present

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.php
    - robertdebock.mysql
    - robertdebock.httpd
